<?php

return [
    [
        'category_id' => '1',
        "title" => "SpotifyWeb",
        "author" => "Alessio Abbati",
        "creation_date" => "2023-03-22",
        "last_update" => "2023-03-27",
        "collaborators" => "",
        "description" => "clone of spotify",
        "languages" => "HTML - CSS",
        "link_github" => "https://github.com/AlessioAbbati/html-css-spotifyweb.git",
    ],
    [
        'category_id' => '1',
        "title" => "Minefield",
        "author" => "Alessio Abbati",
        "creation_date" => "2023-04-26",
        "last_update" => "2023-04-26",
        "collaborators" => "",
        "description" => "clone of minefield",
        "languages" => "HTML - CSS - JS",
        "link_github" => "https://github.com/AlessioAbbati/js-campominato-dom.git",
    ],
    [
        'category_id' => '1',
        "title" => "Social Posts",
        "author" => "Alessio Abbati",
        "creation_date" => "2023-05-03",
        "last_update" => "2023-05-03",
        "collaborators" => "",
        "description" => "clone of social",
        "languages" => "HTML - CSS - JS",
        "link_github" => "https://github.com/AlessioAbbati/js-social-posts.git",
    ],
    [
        'category_id' => '1',
        "title" => "Boolzapp",
        "author" => "Alessio Abbati",
        "creation_date" => "2023-05-10",
        "last_update" => "2023-05-16",
        "collaborators" => "",
        "description" => "clone of whatsapp",
        "languages" => "HTML - CSS - VUE.JS",
        "link_github" => "https://github.com/AlessioAbbati/vue-boolzapp.git",
    ],
    [
        'category_id' => '1',
        "title" => "Boolflix",
        "author" => "Alessio Abbati",
        "creation_date" => "2023-05-24",
        "last_update" => "2023-05-26",
        "collaborators" => "",
        "description" => "clone of netflix",
        "languages" => "HTML - VUE.JS",
        "link_github" => "https://github.com/AlessioAbbati/vite-boolflix.git",
    ],
    [
        'category_id' => '1',
        "title" => "Football League",
        "author" => "Alessio Abbati",
        "creation_date" => "2023-05-29",
        "last_update" => "2023-06-06",
        "collaborators" => "",
        "description" => "clone of football league page",
        "languages" => "HTML - VUE.JS",
        "link_github" => "https://github.com/AlessioAbbati/proj-html-vuejs.git",
    ],
    [
        'category_id' => '2',
        "title" => "Travel Agency",
        "author" => "Alessio Abbati",
        "creation_date" => "2023-07-04",
        "last_update" => "2023-07-04",
        "collaborators" => "Felice D'Arcangelo - Lamberto Neri - Nicola Soggiu - Giulio D'Angelo - Domenico Ferrari",
        "description" => "clone of travel agency",
        "languages" => "PHP - BLADE",
        "link_github" => "https://github.com/AlessioAbbati/laravel-boolean.git",
    ],
    
];